<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Admin1.aspx.vb" Inherits="Admin1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
       <link href="assets/css/bootstrap5.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {
            height: 24px;
        }
        .auto-style3 {
            width: 503px;
        }
        .auto-style5 {
            width: 123%;
            height: 400px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
          <asp:Panel ID="Panel1" runat="server" BackColor="#0066CC" Height="130px" Width="3026px" >
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; 
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="XX-Large"  Text="WELCOME ADMIN" ForeColor="Black" ></asp:Label>
                <br />
                <br />
                <br />
            </asp:Panel>
          <p>
              &nbsp;</p>
          <table class="auto-style5">
              <tr>
                  <td class="auto-style1" colspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <br />
                     
                      <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="6" DataSourceID="SqlDataSource1" Font-Size="Smaller" ForeColor="#333333" Height="16px" Width="219px" AutoGenerateDeleteButton="True" DataKeyNames="fname" BorderColor="#333333" BorderStyle="Solid" CellSpacing="14">
                          <Columns>
                              <asp:BoundField DataField="prefix" HeaderText="prefix" SortExpression="prefix" />
                              <asp:BoundField DataField="fname" HeaderText="fname" SortExpression="fname" ReadOnly="True" />
                              <asp:BoundField DataField="father_spouse_name" HeaderText="father_spouse_name" SortExpression="father_spouse_name" />
                              <asp:BoundField DataField="lname" HeaderText="lname" SortExpression="lname" />
                              <asp:BoundField DataField="mother_name" HeaderText="mother_name" SortExpression="mother_name" />
                              <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
                              <asp:BoundField DataField="gender" HeaderText="gender" SortExpression="gender" />
                              <asp:BoundField DataField="marital_status" HeaderText="marital_status" SortExpression="marital_status" />
                              <asp:BoundField DataField="citizenship" HeaderText="citizenship" SortExpression="citizenship" />
                              <asp:BoundField DataField="occupation" HeaderText="occupation" SortExpression="occupation" />
                              <asp:BoundField DataField="passport_no" HeaderText="passport_no" SortExpression="passport_no" />
                              <asp:BoundField DataField="voterid_no" HeaderText="voterid_no" SortExpression="voterid_no" />
                              <asp:BoundField DataField="drivinglicense_no" HeaderText="drivinglicense_no" SortExpression="drivinglicense_no" />
                              <asp:BoundField DataField="aadhar_no" HeaderText="aadhar_no" SortExpression="aadhar_no" />
                              <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                              <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                              <asp:BoundField DataField="district" HeaderText="district" SortExpression="district" />
                              <asp:BoundField DataField="zip" HeaderText="zip" SortExpression="zip" />
                              <asp:BoundField DataField="state" HeaderText="state" SortExpression="state" />
                              <asp:BoundField DataField="country" HeaderText="country" SortExpression="country" />
                              <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                              <asp:BoundField DataField="mobileno" HeaderText="mobileno" SortExpression="mobileno" />
                              <asp:BoundField DataField="teleno" HeaderText="teleno" SortExpression="teleno" />
                              <asp:BoundField DataField="person_type" HeaderText="person_type" SortExpression="person_type" />
                              <asp:BoundField DataField="prefix1" HeaderText="prefix1" SortExpression="prefix1" />
                              <asp:BoundField DataField="first_name" HeaderText="first_name" SortExpression="first_name" />
                              <asp:BoundField DataField="mname" HeaderText="mname" SortExpression="mname" />
                              <asp:BoundField DataField="last_name" HeaderText="last_name" SortExpression="last_name" />
                              <asp:BoundField DataField="passport" HeaderText="passport" SortExpression="passport" />
                              <asp:BoundField DataField="voterid" HeaderText="voterid" SortExpression="voterid" />
                              <asp:BoundField DataField="drivinglicense" HeaderText="drivinglicense" SortExpression="drivinglicense" />
                              <asp:BoundField DataField="aadhar" HeaderText="aadhar" SortExpression="aadhar" />
                              <asp:BoundField DataField="declare1" HeaderText="declare1" SortExpression="declare1" />
                              <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
                              <asp:BoundField DataField="place" HeaderText="place" SortExpression="place" />
                          </Columns>





                          <HeaderStyle BorderColor="#333333" BorderStyle="Solid" BorderWidth="1px" CssClass="column" />
                          <RowStyle BorderColor="#333333" BorderStyle="Solid" BorderWidth="1px" />
                      </asp:GridView>

                




                      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CKYC_MainConnectionString %>" SelectCommand="SELECT * FROM [dataentry]"
                            ></asp:SqlDataSource>
                




                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                      <br />
                  </td>
              </tr>
              <tr>
                  <td class="auto-style3">&nbsp;</td>
                  <td>&nbsp;</td>
              </tr>
          </table>
    </form>
</body>
</html>